#!/usr/bin/env python3

import sys
import socket
import selectors
import traceback
from server_message import Message
import logging
logging.basicConfig(filename="log.txt", level=logging.DEBUG)
from config import PORT, HOST

sel = selectors.DefaultSelector()


def accept_wrapper(sock):
    """accepts the connection on the server socket and register to read the message from the client"""
    conn, addr = sock.accept()  # Should be ready to read
    logging.DEBUG(f"Accepted From {addr}")
    print(f"Accepted connection from {addr}")
    conn.setblocking(False)
    message = Message(sel, conn, addr)
    sel.register(conn, selectors.EVENT_READ, data=message)


host, port = HOST, PORT

lsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
# Avoid bind() exception: OSError: [Errno 48] Address already in use
lsock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
lsock.bind((host, port))
lsock.listen()
lsock.setblocking(False)
sel.register(lsock, selectors.EVENT_READ, data=None)

try:
    while True:
        events = sel.select(timeout=None)
        for key, mask in events:
            if key.data is None:
                accept_wrapper(key.fileobj)
            else:
                message = key.data
                try:
                    message.process_events(mask)
                except Exception:
                    print(
                        f"Main: Error: Exception for {message.addr}:\n"
                        f"{traceback.format_exc()}"
                    )
                    message.close()
except KeyboardInterrupt:
    print("Caught keyboard interrupt, exiting")
finally:
    sel.close()
